INSERT INTO _map VALUES
       ('PMF', 'compradores', 'compradores', 26, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'centros_educativos', 'centros_educativos', 25, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'centros_reuniones', 'centros_reuniones', 24, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'centros_salud', 'centros_salud', 23, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'comunidades', 'comunidades', 22, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'parcelas', 'parcelas', 21, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'informacion_general', 'informacion_general', 20, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'limites_parcela', 'limites_parcela', 19, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'fuentes_comunitarias', 'fuentes_comunitarias', 18, 'true', NULL, NULL, '', 'pmf', NULL),

       ('PMF', 'aldeas_PMF', 'aldeas_PMF', 17, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'areas_protegidas_2011_VC', 'areas_protegidas_2011_VC', 16, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'caserios_comunidades_PMF', 'caserios_comunidades_PMF', 15, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'curvas_nivel_10m_PMF', 'curvas_nivel_10m_PMF', 14, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'departamentos', 'departamentos', 13, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'equipamientos_VC', 'equipamientos_VC', 12, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'honduras', 'honduras', 11, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'municipios_VC', 'municipios_VC', 10, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'oceano', 'oceano', 9, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'paises_limitrofes', 'paises_limitrofes', 8, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'puertos_aeropuertos_VC', 'puertos_aeropuertos_VC', 7, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'rios_PMF', 'rios_PMF', 6, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'usos_suelo_2003_PMF', 'usos_suelo_2003_PMF', 5, 'true', NULL, NULL, '', 'pmf', NULL),
       ('PMF', 'viario_PMF', 'viario_PMF', 4, 'true', NULL, NULL, '', 'pmf', NULL);